Repository melvio/hopla, pull requests merged in 2021-09, with the labels that each got.

#58 Create CONTRIBUTING.md
  .github/docs/CONTRIBUTING.md
Labels: improvement/healthy-repository

#60 Improved documentation of the cli
  README.md
  src/hopla/cli/auth.py
  src/hopla/cli/complete.py
  src/hopla/cli/config.py
  src/hopla/cli/feed.py
  src/hopla/cli/groupcmds/add.py
  src/hopla/cli/groupcmds/api.py
  src/hopla/cli/groupcmds/buy.py
  src/hopla/cli/groupcmds/get.py
  src/hopla/cli/groupcmds/set.py
  src/hopla/cli/request.py
  src/hopla/cli/support_development.py
  src/hopla/cli/version.py
Labels: documentation

#76 Refactored requests_helper and provided unittest
  src/hopla/cli/feed.py
  src/hopla/cli/groupcmds/add.py
  src/hopla/cli/groupcmds/api.py
  src/hopla/cli/groupcmds/buy.py
  src/hopla/cli/groupcmds/get_user.py
  src/hopla/cli/support_development.py
  src/hopla/hoplalib/clickhelper.py
  src/hopla/hoplalib/requests_helper.py
  src/tests/hoplalib/test_requests_helper.py
Labels: enhancement

#81 Added FeedingStatus functionality and tests
  src/hopla/hoplalib/pethelper.py
  src/tests/hoplalib/test_pethelper.py
Labels: enhancement

#87 Give request classes a shared default_headers
  src/hopla/cli/groupcmds/add.py
  src/hopla/cli/groupcmds/get_user.py
  src/hopla/hoplalib/http.py
  src/hopla/hoplalib/zoo/petcontroller.py
Labels: enhancement

#95 enhancement/93 get group cli command
  src/hopla/__init__.py
  src/hopla/cli/get_group.py
  src/tests/cli/test_get_group.py
Labels: enhancement, get-group

#101 Moved todo comment to github
  src/hopla/cli/groupcmds/buy.py
Labels: documentation, enhancement

#110 Moved CONTRIBUTING.md
  .github/CONTRIBUTING.md
Labels: documentation

#108 Fix potential capitalization error
  README.md
Labels: documentation

#111 Increase README.md quality
  README.md
Labels: documentation, enhancement

#115 Added makefile examples and fixed old ones
  Makefile.examples
Labels: documentation, code-quality

#118 Improved documentation and changed loglevel
  src/hopla/cli/request.py
Labels: documentation, hopla-request

#121 feature/85 add feed until out of food option
  src/hopla/__init__.py
  src/hopla/cli/feed.py
  src/hopla/cli/feed_all.py
  src/hopla/cli/get_group.py
  src/hopla/hoplalib/zoo/feeding_clickhelper.py
  src/hopla/hoplalib/zoo/foodmodels.py
  src/hopla/hoplalib/zoo/petdata.py
  src/hopla/hoplalib/zoo/zoofeeding_algorithms.py
  src/tests/cli/test_feed.py
  src/tests/cli/test_feed_all.py
  src/tests/hoplalib/zoo/test_petcontroller.py
  src/tests/hoplalib/zoo/test_petdata.py
  src/tests/hoplalib/zoo/test_petmodels.py
  src/tests/hoplalib/zoo/test_zoofeeding_algorithms.py
Labels: hopla-feed, hopla-feed-all

#125 enhancement/102 make hopla available on pypi
  .github/CONTRIBUTING.md
  Makefile
  README.md
  pyproject.toml
  setup.cfg
Labels: enhancement

#134 Add the is_flag for hopla-buy
  src/hopla/cli/buy/enchanted_armoire.py
Labels: hopla-buy-enchanted-armoire

#151 codequality/150 flake8
  .github/workflows/ci-lint-and-test.yml
  .github/workflows/flake8.ini
  Makefile
  requirements.txt
  setup.py
  src/hopla/__init__.py
  src/hopla/cli/get_user/stats.py
  src/hopla/hoplalib/clickhelper.py
  src/hopla/hoplalib/requests_helper.py
  src/tests/cli/buy/test_enchanted_armoire.py
  src/tests/cli/get_user/test_info.py
  src/tests/hoplalib/test_hoplaversion.py
  src/tests/hoplalib/zoo/test_foodmodels.py
  src/tests/hoplalib/zoo/test_petdata.py
  src/tests/test_kickstarter.py
  src/tests/testutils/user_test_utils.py
Labels: code-quality

#155 Increase code cov minimum req. to 70%
  .github/workflows/pytest.ini
  Makefile
  setup.py
Labels: code-quality, continuous-integration

#158 Extracted style_guile.md fro CONTRIBUTING.md
  .github/CONTRIBUTING.md
  .github/style_guide.md
Labels: documentation
